// Code generated by MockGen. DO NOT EDIT.
// Source: cdc/sinkv2/eventsink/txn/backend.go

// Package mock_txn is a generated GoMock package.
package mock_txn

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	eventsink "github.com/pingcap/tiflow/cdc/sinkv2/eventsink"
)

// MockBackend is a mock of Backend interface.
type MockBackend struct {
	ctrl     *gomock.Controller
	recorder *MockBackendMockRecorder
}

// MockBackendMockRecorder is the mock recorder for MockBackend.
type MockBackendMockRecorder struct {
	mock *MockBackend
}

// NewMockBackend creates a new mock instance.
func NewMockBackend(ctrl *gomock.Controller) *MockBackend {
	mock := &MockBackend{ctrl: ctrl}
	mock.recorder = &MockBackendMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBackend) EXPECT() *MockBackendMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockBackend) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockBackendMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockBackend)(nil).Close))
}

// Flush mocks base method.
func (m *MockBackend) Flush(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Flush", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Flush indicates an expected call of Flush.
func (mr *MockBackendMockRecorder) Flush(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Flush", reflect.TypeOf((*MockBackend)(nil).Flush), ctx)
}

// MaxFlushInterval mocks base method.
func (m *MockBackend) MaxFlushInterval() time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MaxFlushInterval")
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// MaxFlushInterval indicates an expected call of MaxFlushInterval.
func (mr *MockBackendMockRecorder) MaxFlushInterval() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MaxFlushInterval", reflect.TypeOf((*MockBackend)(nil).MaxFlushInterval))
}

// OnTxnEvent mocks base method.
func (m *MockBackend) OnTxnEvent(e *eventsink.TxnCallbackableEvent) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OnTxnEvent", e)
	ret0, _ := ret[0].(bool)
	return ret0
}

// OnTxnEvent indicates an expected call of OnTxnEvent.
func (mr *MockBackendMockRecorder) OnTxnEvent(e interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnTxnEvent", reflect.TypeOf((*MockBackend)(nil).OnTxnEvent), e)
}
